baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Josh Potts'

theme='tailwind'

[author]
name='Josh Potts'

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  showReadingTime = true
  description='A blog site'
  subtitle='A blog site'
  keywords = "hugo, blog, technology"
  toc=false

  [params.header]
    logo = "logo.jpg"

  [params.footer]
    since = 2025
    poweredby = true

  [params.social_media]
    [[params.social_media.items]]
      enabled = true
      title = 'LinkedIn'
      icon = 'brand-linkedin'
      link = 'https://www.linkedin.com/in/josh-potts-tn/'
    [[params.social_media.items]]
      enabled=true
      title = 'Github'
      icon = 'brand-github'
      link = 'https://github.com/jlpdeveloper'
  [pwa]
    enabled = true
    icon = "logo.png" # should be in assets
    icon_sizes = [192, 512]
    [[pwa.manifest]]
      description = 'Josh Potts Blog Site'

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "/about.md"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

